/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueo;

import javax.swing.JOptionPane;

/**
 *
 * @author JAOC
 */
public class Ventana extends javax.swing.JFrame {

    private Parqueadero p;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        p = new Parqueadero();
        initComponents();
        this.dispoCarro();
        this.dispoMoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cjPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btAddMoto = new javax.swing.JButton();
        btAddCarro = new javax.swing.JButton();
        btRetMoto = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTmCarro = new javax.swing.JLabel();
        lbTmMoto = new javax.swing.JLabel();
        btRetCarro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("PARQUEADERO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 110, 14);

        cjPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(cjPlaca);
        cjPlaca.setBounds(80, 70, 70, 20);

        jLabel2.setText("PLACA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 50, 14);

        btAddMoto.setText("ADICIONAR MOTO");
        btAddMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddMotoActionPerformed(evt);
            }
        });
        getContentPane().add(btAddMoto);
        btAddMoto.setBounds(230, 50, 140, 23);

        btAddCarro.setText("ADICIONAR CARRO");
        btAddCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCarroActionPerformed(evt);
            }
        });
        getContentPane().add(btAddCarro);
        btAddCarro.setBounds(230, 90, 140, 23);

        btRetMoto.setText("RETIRAR MOTO");
        btRetMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetMotoActionPerformed(evt);
            }
        });
        getContentPane().add(btRetMoto);
        btRetMoto.setBounds(230, 150, 150, 23);

        btExit.setText("SALIR");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit);
        btExit.setBounds(320, 260, 73, 23);

        jLabel3.setText("CUPOS DISPONIBLES CARROS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 250, 190, 14);

        jLabel4.setText("CUPOS DISPONIBLES MOTOS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 270, 190, 14);

        lbTmCarro.setText("18");
        getContentPane().add(lbTmCarro);
        lbTmCarro.setBounds(230, 250, 20, 14);

        lbTmMoto.setText("10");
        getContentPane().add(lbTmMoto);
        lbTmMoto.setBounds(230, 270, 30, 14);

        btRetCarro.setText("RETIRAR CARRO");
        btRetCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetCarroActionPerformed(evt);
            }
        });
        getContentPane().add(btRetCarro);
        btRetCarro.setBounds(230, 190, 150, 23);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjPlacaActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        this.Salir();
    }//GEN-LAST:event_btExitActionPerformed

    private void btRetMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetMotoActionPerformed
        // TODO add your handling code here:
        this.exitMoto();
    }//GEN-LAST:event_btRetMotoActionPerformed

    private void btAddCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCarroActionPerformed
        // TODO add your handling code here:
        this.addCarro();
    }//GEN-LAST:event_btAddCarroActionPerformed

    private void btAddMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddMotoActionPerformed
        // TODO add your handling code here:
        this.addMoto();
    }//GEN-LAST:event_btAddMotoActionPerformed

    private void btRetCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetCarroActionPerformed
        // TODO add your handling code here:
        this.exitCarro();
    }//GEN-LAST:event_btRetCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private void Salir() {
        System.out.println("SALIR");
        System.exit(0);
    }

    private void addMoto() {
        String laPlaca = cjPlaca.getText();
        Vehiculo moto = new Vehiculo(laPlaca, "MOTO");
        boolean inserta = p.addMoto(moto);
        if (inserta) {
            JOptionPane.showMessageDialog(this, "MOTO ADICIONADO");
            this.dispoMoto();
        } else {
            JOptionPane.showMessageDialog(this, "MOTO YA ADICIONADA");
        }
    }

    private void addCarro() {
        String laPlaca = cjPlaca.getText();
        Vehiculo carro = new Vehiculo(laPlaca, "CARRO");
        boolean inserta = p.addCarro(carro);
        if (inserta) {
            JOptionPane.showMessageDialog(this, "CARRO ADICIONADO");
            this.dispoCarro();
        } else {
            JOptionPane.showMessageDialog(this, "CARRO YA ADICIONADO");
        }
    }

    private void exitMoto() {
        String laPlaca = cjPlaca.getText();
        long valorPagar = p.salir(laPlaca, "MOTO");
        if (valorPagar >= 0) {
            JOptionPane.showMessageDialog(this, "PAGA $" + valorPagar);
            this.dispoMoto();
        } else {
            JOptionPane.showMessageDialog(this, "NO EXISTE");
        }

    }

    private void exitCarro() {
        String laPlaca = cjPlaca.getText();
        long valorPagar = p.salir(laPlaca, "CARRO");
        if (valorPagar >= 0) {
            JOptionPane.showMessageDialog(this, "PAGA $" + valorPagar);
            this.dispoCarro();
        } else {
            JOptionPane.showMessageDialog(this, "NO EXISTE");
        }

    }

    private void dispoMoto() {
        int cupoMoto = p.cuposDisponiblesMoto();
        this.lbTmMoto.setText(""+cupoMoto);
    }

    private void dispoCarro() {
        int cupoCarro = p.cuposDisponiblesCarro();
        this.lbTmCarro.setText(""+cupoCarro);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCarro;
    private javax.swing.JButton btAddMoto;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btRetCarro;
    private javax.swing.JButton btRetMoto;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbTmCarro;
    private javax.swing.JLabel lbTmMoto;
    // End of variables declaration//GEN-END:variables
}
